type: editor
showTerminals: false
showExplorer: true
yourResultPort: 3001
yourResultPath: "/"
answerPort: 3004
answerPath: "/"
openFiles:
  - /app.js
  - /content.js
  - /server.js
  - /lib/index.js
terminals:
  - name: Terminal
    commands:
      - gulp --silent
answerCommands:
  - sudo sed -i 's/3000/3004/g' server.js
  - pm2 start npm  --name 'HO-M12-T02-00' -- start
  - pm2 save
